@startuml
autonumber

skinparam sequence {
ArrowColor gray
ActorBorderColor gray
LifeLineBorderColor black
}
skinparam shadowing false
hide footbox

participant 醫院 #d1ebf1
participant NHI  #D5E8D4
醫院 -> NHI: 上傳癌藥事前審查報告（Bundle TWPAS）
醫院 -> NHI: 上傳癌藥事前審查相關文件（意即Bundle TWPAS所參照的附件及影像）
alt 上傳成功
    醫院 -> NHI: 取得上傳成功訊息
    alt 審核通過
        醫院 -> NHI: 取得審核通過訊息
    else 審核失敗
        醫院 -> NHI: 取得審核未通過訊息
    end
else 上傳失敗
    醫院 -> NHI: 取得上傳失敗訊息
end
@enduml